### ISSUE TITLE
Nominatim connection is lost

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#1006] opened 2023-08-06 04:11 UTC
### Description

Since days I cannot search within OSM, it gives no results.
I tried Nominatim search site and it works: https://nominatim.openstreetmap.org/ui/search.html
And https://www.openstreetmap.org/#map=13/47.2939/17.5988 also works

But not when I am editing in OSM and I need to find a location.
There is no error message.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Firefox 116.0.1

### The OS you're using

Windows 11 with latest updates

### Steps to reproduce

Search a location.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=FOMI_2007_2010&datasets=fbRoads,msBuildings&disable_features=landuse,boundaries,pistes,aerialways,past_future,others&map=16.60/47.30270/17.59411

**Comment by Bonkles** [comment] 2023-08-09 14:54
Closing as a dupe of #1007

**Closed by Bonkles** 2023-08-09 14:54 UTC
