### ISSUE TITLE
Typing into a Edit Feature text field causes data loss

### ISSUE THREAD

**Issue by Sellyme** [facebook/Rapid#1084] opened 2023-08-31 08:37 UTC
### Description

Under certain circumstances address information that has just been filled out for a feature in the editor will end up malformed in some way. I've mainly observed this when entering a multi-digit house number into the address field, where only the first digit saves after navigating away from the feature (e.g., `21` becomes `2`), and any additional address information added *after* typing the second digit doesn't save at all.

In addition (or perhaps, causing) the data loss, the `Edit feature` UI seems to freeze after entering any digits at all - the `+` buttons under `Tags` and `Relations` no longer respond, the delete icons on various fields no longer respond, and attempting to use the up or down arrows on a numerical field like `Height (Metres)` causes `NaN` to appear in the input box. Manually typing into any of these fields still responds, but none of the typed data will persist after deselecting the feature.

Similar behaviour to this appears to occur for many different text fields available in the Edit Feature panel (e.g., Description, Website, etc.) - the UI immediately stops behaving as expected after the first character is entered, and any subsequently-entered text in any field will be lost.

I've only ever experienced this bug after saving a changeset and continuing to edit in the same session; refreshing the page will immediately resolve the issue (until I next upload a changeset).

I'm able to reproduce this error very reliably in both Firefox (where I've done the majority of my testing) and Chrome (v116.0.5845.140).

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Firefox 117.0b7

### The OS you're using

Windows 11

### Steps to reproduce

* Enable the "Microsoft Buildings" Assist feature
* Click on and press "A" for several suggested buildings
* Upload your changeset to the OSM servers
* After the changeset has saved, click on one of the newly-mapped buildings
* Enter a **two-digit** number into the "123" (house number) input box in the "Address" field. Note that this is the user-friendly field, **not** manually creating an addr:housenumber tag.
* Immediately click on a neutral area in the map to deselect the building.
* Click on the building again, and observe the address number being truncated to only the first digit that was entered.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=msBuildings&disable_features=boundaries&id=w1203877057&map=20.04/-35.54988/138.62039&offset=0.65,-0.6

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by nickrsan** [comment] 2023-08-31 19:17
I just experienced similar issues while adding a POI in Firefox 116.0.3 on Windows 10. I wasn't sure if I'd be able to fully reproduce, so I'm glad your report is here. In my case, I:
1. selected a Thai Restaurant preset.
2. The information correctly showed up in the "Fields" section and in the "Tags" section, but after adding website, phone, and address in the "Fields' section, none of that information propagated to the "Tags" section.
3. Toggling the tags to text and back to the editor didn't change anything,
4. and the + button below the tags is nonresponsive.

I get no errors or warnings in the console when clicking it, but further up the console I have two errors "Error: Promised response from onMessage listener went out of scope 164 ta_bg.js:44:23" - I don't know if it's related, but in case it is.

I'm not sure if this is the same issue or not, but the behaviors related to +/- seemed similar, so I thought I'd mention it here first

**Comment by jjiglesiasg** [comment] 2023-08-31 23:05
This seems to be happening with several other Tag data, not just addresses. Just the first digit remain

**Comment by bhousel** [comment] 2023-08-31 23:13
Yep, I am able to reproduce and working on the fix now..
The Entity Inspector (sidebar content for working with OSM data) gets in a bad state after a refresh, which happens after the user saves.

**Comment by nickrsan** [comment] 2023-08-31 23:15
That covers my instance too - I'd finished one changeset and the errors happened while making a second changeset.

**Closed** 2023-08-31 23:50 UTC
Labels: bug, top-priority

**Comment by bhousel** [comment] 2023-09-01 02:26
Thanks for helping us test and track this down!
We'll try to get a release out asap.

If you're interested in trying a canary build that includes the fix, you can try the latest build here:
https://rapideditor.org/rapid/a8217da-16.x-/index.html
