### ISSUE TITLE
pressing "M" while "rotate" is active does nothing

### ISSUE THREAD

**Issue by sybenx** [facebook/Rapid#852] opened 2023-03-22 14:17 UTC
### Description

It should approve of the rotation and start moving the object

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v111.0

### Steps to reproduce

1. Select an object
2. Press R and rotate object
3. Press M
4. Nothing happens

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=17.32/40.31353/-111.73071

**Comment by bhousel** [comment] 2023-03-22 14:26
thanks for reporting - this is a duplicate of #818

**Closed by bhousel** 2023-03-22 14:26 UTC
