### ISSUE TITLE
Square corners not working as excepted

### ISSUE THREAD

**Issue by atiannicelli** [facebook/RapiD#683] opened 2022-12-01 15:50 UTC
### Description

If I have a rectangle building with a 5th node that is just a bit outside of the square the validator reports that the building is not square. 
- If I click on the building to square it the "square" option is grayed out and it says that this object can't be squared any more. 
- If I click the "q" it doesn't do anything and reports that the feature can't be squared any more.
- if I go to the validation report and click on "Square this feature" then it moves the node a bit, but doesn't really square the building. But the validation report disappears so apparently it is square enough?? (this might be due to another bug where the building is squared, but doesn't draw the new square building - so really the issue is the first two bullets)

### Version

2.00-alpha.3

### What browser are you seeing the problem on? What version are you running?

Chrome v107.0

### Steps to reproduce

This movie shows what I'm talking about... but now - of course I can't reproduce it.

https://user-images.githubusercontent.com/5851115/205097644-045d8dd5-55ba-49fe-8dd0-a47347aabfcc.mov

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w29797347&map=21.53/42.38858/-71.08270

**Comment by Bonkles** [comment] 2022-12-01 16:20
Most likely a dupe of #682 which is itself already being worked on by the inimitable @bhousel. Will come back around and test this once his fixes are in.

**Comment by Bonkles** [comment] 2022-12-08 18:48
Fixed in alpha 3.2 release that just went live.

**Closed by Bonkles** 2022-12-08 18:48 UTC
