### ISSUE TITLE
Save "Map Features" from previous sessions.

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#1339] opened 2024-02-28 14:48 UTC
### Description

When I open Rapid it comes up with disable_features=boundaries in the URL. I would love it if the disabled features were saved to a cookie or some other way to remember what I had last. The reason for this is that when using rapid with maproulette I am editing the same type of stuff for each task, but each task reopens rapid and this sets the disabled_features back to boundaries. In the specific case that I'm looking at I am opening rapid, then disabling landuse and power features... then I edit and save my changes and then go on to the next map roulette task. This reopens rapid with disable_features=boundaries and I have to go disable the landuse and power features again.
It would be super not to have to go and set the disabled features to the way I like it every time I open rapid.

**Comment by bhousel** [comment] 2024-04-18 22:11
I agree - I just realized this is actually a duplicate of #906

**Closed by bhousel** 2024-04-18 22:11 UTC
