### ISSUE TITLE
Uploading Changes with conflicts may result in tight loop / soft hang

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1366] opened 2024-04-04 17:34 UTC
### Description

Looks like there are potential issues with the conflict resolution portion of the save dialog in Rapid 2.2.5. 

### Screenshots

https://github.com/facebook/Rapid/assets/1887955/ed95008b-e0f3-4164-906f-6c3d78c10889

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Chrome

### The OS you're using

MacOS 14

### Steps to reproduce

This one may take a bit of time to try and reproduce, as it involves conflicts in OSM. 

See the video above for the issue itself- while uploading his changes, @atiannicelli encountered a tight-loop where we just display 0/66 conflicts.... forever. 

Upon refresh, the local changes to the map were dropped and the Alex lost all his work. :( 

### The browser URL at the time you encountered the bug

TBD- will ask Alex for this input

**Comment by bhousel** [comment] 2024-04-18 14:03
yeah this one is painful 😞 
This is a duplicate of #1361

**Closed by bhousel** 2024-04-18 14:03 UTC
