### ISSUE TITLE
Microsoft Buildings not properly conflated with existing OSM buildings

### ISSUE THREAD

**Issue by elevenchars** [facebook/Rapid#1362] opened 2024-04-03 07:52 UTC
### Description

In some(?) cases, it seems like the Microsoft Buildings dataset is not properly conflated/deduplicated with the existing OSM building ways. The result is the Rapid AI buildings overlapping existing buildings. I mentioned this on the OSMUS Slack a few days ago, but it's still happening.

### Screenshots

![Screenshot 2024-04-03 at 02-50-51 Rapid](https://github.com/facebook/Rapid/assets/11055681/43b2e25a-19db-4e65-8846-bf512f239add)

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Firefox 124.0.1

### The OS you're using

Fedora 39 Linux

### Steps to reproduce

1. Enable Microsoft Buildings dataset under the Rapid button
2. Observe duplicated buildings (from what I have seen, 1 OSM building and 1 "Microsoft Buildings" building)

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit?#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.52/30.54712/-97.81878

**Comment by bhousel** [comment] 2024-04-03 16:50
Thanks for reporting, this is a duplicate of #1295

**Closed by bhousel** 2024-04-03 16:50 UTC
