### ISSUE TITLE
UI freezes completely when enabling Mapillary overlay

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#834] opened 2023-03-02 15:48 UTC
### Description

Title says it all :)

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v110.0

### Steps to reproduce

1. Go to URL below
2. Enable Mapillary overlay

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=indoor,boundaries,pistes&id=n9254681279&map=18.00/40.76499/-111.90170

**Comment by Bonkles** [comment] 2023-03-07 18:36
This is a duplicate of #824, which is already fixed. Closing!

**Closed by Bonkles** 2023-03-07 18:36 UTC
Labels: bug
