### ISSUE TITLE
No graphical difference between intermittent and non intermittent elements

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#903] opened 2023-04-05 23:40 UTC
### Description

For mapping waterways and water areas the intermittent and non intermittent tags are a must. However currently V2 show all of them as solid lines or areas. Lakes, Basins, Reservoirs, Water Bodies, Streams, Rivers, etc are important elements to map wordlwide in particular in underdeveloped countries.

Currently is confusing the depiction as solid elements, quite different from RAPID V1 and ID.

Is the dashed/stripped depiction is restored, will be very helpfull.

Thanks

 

### Version

2.0.1

### What browser are you seeing the problem on? What version are you running?

Chrome 10

### The OS you're using

Win 10

### Steps to reproduce

Draw any line or area and use the intermitent=yes tag, no change in the element depiction

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=17.32/-18.18375/-64.08228

**Comment by bhousel** [comment] 2023-04-08 13:53
Thanks , this is a duplicate of #535 
I agree we should put the dashed line styling back for drawing intermittent features.

**Closed by bhousel** 2023-04-08 13:53 UTC
Labels: duplicate
