### ISSUE TITLE
`railway=abandoned` rendered too prominently

### ISSUE THREAD

**Issue by mvexel** [facebook/Rapid#791] opened 2023-02-02 23:15 UTC
### Description

An abandoned railway should be de-emphasized for rendering. Currently it looks pretty much like a normal railway.

Here's abandoned, normal and disused side by side. I can't tell the difference.

<img width="434" alt="image" src="https://user-images.githubusercontent.com/120452/216472401-cc511cc1-fc04-414d-ae22-863346b0e5ca.png">

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Firefox v109.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w7651285&map=18.83/32.54243/-86.21143

**Comment by bhousel** [comment] 2023-04-08 14:33
I think this is a duplicate of #535

**Closed by bhousel** 2023-04-08 14:33 UTC
Labels: good first issue, feature-mapstyle
