### ISSUE TITLE
Unable to save more than 45 feature edits during one session

### ISSUE THREAD

**Issue by VLD190** [facebook/RapiD#710] opened 2022-12-07 22:39 UTC
### Description

I am not sure if this one is a bug, but I was unable to edit more than 45 features during one session. After I reached the maximum edits, RapiD did not allow me to use the shortcut key "A" that allows me to 'use this feature'

There are no error/ warning messages that pop-up, but the button for 'use this feature' changes color from pink to grey.

### Version

2.00-alpha.3.1

### What browser are you seeing the problem on? What version are you running?

Chrome v108.0

### Steps to reproduce

Create more than 45 edits during a rapiD session

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.49/33.92401/-116.54627

**Comment by boothym** [comment] 2022-12-10 23:11
I assume it is actually 50 from this error message: `To help improve OSM data quality, we only allow 50 AI Features to be added in each mapping session.`

That seems to be a duplicate of #109 however surely this limit can raised to something like 100 or 200 at least? Having to save every 50 edits when adding lots of houses in a town or city with few buildings mapped is very tedious.

**Comment by Bonkles** [comment] 2022-12-13 15:54
I'd sure like to investigate ways that we can make AI edits faster and less cumbersome, but this limit was put in place to prevent abuse of the AI datasets (i.e. people just mass-adding everything without checking to see if alignment is good). 

I definitely agree there are improvements we could make. I'll close this issue and put further discussion in #109.

**Closed by Bonkles** 2022-12-13 15:54 UTC
