### ISSUE TITLE
Selection color

### ISSUE THREAD

**Issue by meta-austin** [facebook/Rapid#1570] opened 2024-09-23 18:01 UTC
### Description

The selection highlight really shouldn't be yellow. There are already so many other yellow elements that it make it hard to discern the selected item, especially in dense areas. This is one thing that iD actually does better than RapiD. I'd suggest at least a color change, but some sort of "breathing" animation might help out a lot as well. As for which color, I think there are a few options. The red that both iD and JOSM use works fine, it just has to be a more saturated red than the current color for buildings. Neon pink seems to be reserved for RapiD features, but other bright colors like cyan, bright orange or lime green seem to not conflict as much with RapiD's typical color palette.

**Comment by bhousel** [comment] 2024-09-23 18:05
Thanks @meta-austin , this is kind of a duplicate of #946 and #813, but it's something I'm aware of and want to improve.

I agree it would be great to get the pulsing animation back.  When we switched to the new renderer, it meant that we couldn't use CSS anymore to class the features and make them pulse. The thing I want to build for #1077 would enable this.

**Closed as completed by bhousel** 2024-09-23 18:05 UTC
Labels: duplicate

**Comment by meta-austin** [comment] 2024-09-23 18:29
Ah, my bad, I should have looked just a bit harder. Thanks for the very quick response!
