### ISSUE TITLE
Squaring building fails

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#692] opened 2022-12-05 19:01 UTC
### Description

When attempting to square (q) an obviously unsquare building I just drew, Rapid tells me on the first attempt that it squared the building, but nothing happens in reality. 

When attempting to square it a second time, Rapid tells me it can't be made any more square.

### Version

2.00-alpha3

### What browser are you seeing the problem on? What version are you running?

Firefox 107 Mac

### Steps to reproduce

1. Select an area feature that you would like to square
2. Press "Q"

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-13&map=19.86/40.74180/-111.85901

**Comment by Bonkles** [comment] 2022-12-06 14:41
Duplicate of #683 most likely!

**Comment by Bonkles** [comment] 2022-12-08 18:49
Fixed in alpha 3.2 release that just went live.

**Closed by Bonkles** 2022-12-08 18:49 UTC
