### ISSUE TITLE
Rapid roads dataset is not loading

### ISSUE THREAD

**Issue by bos** [facebook/Rapid#1584] opened 2024-10-12 00:27 UTC
### Description

Inferred roads are not showing up in my client. I assume this is due to a server outage, but I have no idea how to figure this out, or what the best way to report is.

### Version

2.4.0

### Steps to reproduce

Visit Rapid.
No purple road bits.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=17.00/39.20809/-114.77681&background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=indoor,power

**Comment by Bonkles** [comment] 2024-10-15 23:11
Hey @bos! I can't personally repro this, as I've tried it on a couple of different OS/browser combos and all seems well. 

I checked into the specific area you linked here (thanks for supplying the URL) and checked the back-end calls that we're making to obtain roads- they all succeeded, but all came up empty. 

So, it would seem that the case is there's simply no data around here- but have you seen this other places as well?  Specifically, have you seen it in some places before where now you're not getting any road shapes at all?

**Comment by Bonkles** [comment] 2024-10-15 23:12
If you have time, can you go here and let me know if you get some roads? 

https://rapideditor.org/edit#map=17.60/44.51266/-99.99054&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

Here's what I see at this location: 
![image](https://github.com/user-attachments/assets/d2c96223-94a2-49c6-b473-c5b6ea17ba67)

**Comment by Bonkles** [comment] 2024-10-16 14:29
@Scott169 can you provide a URL of where you took that screenshot? That will better let me figure out if this is a server issue or not. 

If you're not able to load the Rapid roads/building features, then you won't get the 'mapwithai' and 'maxar' tags on your changeset- those won't be added until you have added at least one road/building.

**Comment by pieleric** [comment] 2024-10-16 20:09
@Bonkles, I am facing the same issue too: no road shown, anywhere in the world. The buildings show up fine (including the location you've suggested in comment https://github.com/facebook/Rapid/issues/1584#issuecomment-2415322740 ).

One area I know that used to show roads is this one:
https://rapideditor.org/rapid#map=16.43/33.20938/107.54420&background=EsriWorldImagery&datasets=fbRoads,msBuildings

Now it looks like:
![image](https://github.com/user-attachments/assets/df3e4589-be55-44d8-a30e-dff5a409c43d)

**Comment by KataJing** [comment] 2024-10-17 14:56
Also met the same issue from about one week ago. Cannot see any roads including above hyperlinks.
Seems something happen in source. I am also a mapwithai of JOSM user. The similar issue occurred, it showed server cannot connect.

**Comment by Bonkles** [comment] 2024-10-17 15:34
Can confirm that one of our internal DBs has been impacted, causing the loss of our ability to serve roads. I'm working on repairing the infra, but no ETA yet on how long this will take. 

Thank you all for the bug reports!

**Comment by jjiglesiasg** [comment] 2024-10-24 02:05
Seems that this issue is more complex that originally thought. Not pushing, just good vibes so yo can deal with this somehow nightmare.

**Comment by Bonkles** [comment] 2024-10-24 13:00
Yep, this one is proving tricky. Plus, one of the folks that can help us resolve the issue has been out sick for several days. Really unlucky timing, but still working on it.

**Comment by bos** [comment] 2024-11-04 17:14
How's restoring the db coming along?

**Comment by Bonkles** [comment] 2024-11-04 18:37
Not well, unfortunately. We have all the piece-parts we need to get the data flowing again, but there are a lot of gotchas to 'standing an existing DB scrape back up' vs. 'starting one from scratch'. We're just doing tons of waiting for assistance from internal infra groups, as we're a bit of an outlier case (in that we ship our data to a public endpoint). 

Super frustrating and I wish it were going faster, but I'm still on this pushing on this as hard as I can each day.

**Comment by bos** [comment] 2024-11-04 19:26
Thanks Ben, appreciate the persistence.

**Comment by Bonkles** [comment] 2024-11-07 14:38
Update- we've had a couple nice breakthroughs with the data pipeline and the roads data is once again landing in a database from which we can serve. Next step is to migrate all the code references from the old, defuct database to this new one, test the changes in staging, and then roll out to production. Could be a few more days, but I'm on much firmer ground as to how to proceed from here. 

Thanks all for your patience!

**Comment by bos** [comment] 2024-11-08 18:27
That's great news! Mapping in the old school way, without these features, is certainly fun and calming, but it's soooo sloooow in comparison.

**Comment by bos** [comment] 2024-11-08 20:32
I just now am seeing inferred roads show up!

**Comment by Bonkles** [comment] 2024-11-08 20:57
Woohoo, I was hoping they'd start flowing by end-of-day, then I would make a triumphant post letting y'all know. So I guess this is that post. :-)

**Comment by Scott169** [comment] 2024-11-08 21:03
I saw the inferred roads. Confirmed that this issue is solved.

**Comment by jjiglesiasg** [comment] 2024-11-09 00:15
Looks like inferred roads are back. Reporting from #Bolivia. Congrats guys nice job to restore all these data.

Best Regards

**Comment by jjiglesiasg** [comment] 2024-11-09 00:17
> That's great news! Mapping in the old school way, without these features, is certainly fun and calming, but it's soooo sloooow in comparison.

True, but even without the inferred data, I feel that Rapid is like an ID on steroids, in particular in Power User mode

**Comment by Bonkles** [comment] 2024-12-23 16:39
Roads have been fixed for a while now- closing!

**Closed by Bonkles** 2024-12-23 16:39 UTC
Labels: data-roads, feature-internal
