### ISSUE TITLE
Key bindings are broken

### ISSUE THREAD

**Issue by bos** [facebook/Rapid#1266] opened 2023-12-20 23:45 UTC
### Description

Since a release today, most (but not all?) keyboard input goes to the search box, and many normal editing capabilities are thus broken.

### Version

2.2.0

### What browser are you seeing the problem on? What version are you running?

Safari v17.2

### The OS you're using

mac

### Steps to reproduce

Type any key such as "a" and it unavoidably goes into the search box instead of triggering an edit action.

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=indoor,landuse,boundaries,power&map=18.00/34.62415/-115.16238

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15

**Comment by mxxcon** [comment] 2023-12-21 01:06
Duplicate of #1265

**Comment by Bonkles** [comment] 2023-12-21 02:37
@mxxcon is right, this appears to be a dupe- closing this and will put updates in #1265. Thanks for reporting!

**Closed by Bonkles** 2023-12-21 02:37 UTC
