### ISSUE TITLE
Cannot pan in Mapillary image

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#1049] opened 2023-08-25 11:53 UTC
### Description

Mapillary image seems locked, can not click and drag to pan

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome v115.0

### The OS you're using

win

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=EsriWorldImageryClarity&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.24/32.71785/-117.16475&photo=mapillary/498074064869543&photo_overlay=mapillary

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by Bonkles** [comment] 2023-09-27 14:43
This is a duplicate of an earlier stretch goal that I created during the 2.0 dev cycle- closing this one and will track progress in #508

**Closed by Bonkles** 2023-09-27 14:43 UTC
