### ISSUE TITLE
Rapid v2.0 public beta - Issues

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#804] opened 2023-02-15 17:34 UTC
Great Improvement, some issues detected so far (Will add more once I find them)

a) When you select a way/waterway it only took the nodes, not the way at such if the way have several nodes close enough.
b) Scrolling wheel is now up and down and not zoom in and out, as used to be.
c) Some areas like Dams are depicted as lines, instead of areas
d) On two chossen ways if you try to joint them, do not give you that possibility, just continue or disconnect (There is an indicated junction node, but could easily be two nodes together without warning, that do not allow to merge the two ways/waterways.
e) Still not able to choose the language for RAPID app depiction. By default goes to Spanish (in my case), even that my Windows software is in English, and I regulary edit in such language in ID.
f) The joining of the two terminal nodes of any way is not so easy, and requires sometimes several attents. Not proximity joining  how used to be.
g) Intermitent waterways are depicted as solid lines instead of dashed ones.
h) Nice feature to be able to draw a continuos line without seeing all the nodes in such line (more seamless) (Not AI Suggested)
i) The direction of the way/waterway should be in the direction that it was draw sequentialy (from Node 1 to NodeXX), it depict inverse to that sequence.
j) Love the depiction of the name of an area in small blue lettering, if named (Nice add)
k) Mouse Left Click and Right Click, both pan the image, in ID just Left one does. Consider using right click for another function. (scroll wheel also pan but just up and down, consider going back to zooming).
l) Water bodies (natural=water) are both in Water Bodies and Natural Features, should not be in just one? I guess
m) A Ridge is depicted as a thick grey line, instead of the usual thin green line. A cliff also depicted as a thick grey line instead of the usual thin one.

n) Some closed areas with name, now seems to be represented by the area itself plus a centroid node, was this done in porpouse? it is a little big confusing...
o) Paths and footways are depicted in the same way. In ID paths are thin grey and footways thin white (important for backcountry and outdoor).
p) Some suggested AI data could not be selected, neither discarded or accepted. (Shown as dupe n9867068207)
q) Some boundaries are depicted just as a solid grey line but do not show at all that that they belong to a Relation, neither shown an area.
r) Hot Springs are depicted as a white node instead with the hot water logo of ID

**Comment by Bonkles** [comment] 2023-02-16 17:57
Thank you for these submissions! We do have bugs for some of the issues that you reported: 

b) scroll wheel is not zooming (#680)
g) intermittent waterways styling (#535)
e) Translations for RapiD Strings (#206) (admittedly, this is an old issue that I *really* want to fix) 
q) Boundaries not showing that they are part of a relation(#536) 

### New Issues Opened
I have opened the following new issues to cover some of the issues you raised above (we try to track issues individually, it's much easier to document and track as we fix things). 

d,f) (joining nodes): #807 
h) (styling nodes during draw gesture): #808
m) (Styling of ridges and cliffs): #809, #810
o) (Styling for footpaths vs paths): #811
p) (nodes should not appear in the rapid roads layer): #812

### Working as Intended: 
 k) This was added as an undocumented feature- right-clicking and moving will pan, regardless of what your mouse is over (this is helpful when viewing a very very dense map, because left-clicking and moving the mouse will try to move the feature you clicked on, instead of panning the map). Try right-clicking to pan around in a very dense area! 

If you right-click without moving the mouse, the same context menu functionality should still work for you just like it did before in v1. 

 n) Closed areas with a name now do have a centroid node- this is intentional! Can you describe what is confusing about it? 

### Need more information

I either cannot reproduce or need more information about a few of the things you described:

c) dams look like areas to me, for example the hoover dam in Arizona: https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=r1275469&map=19.03/36.01574/-114.73806)
i)  I drew a new waterway and the direction appears appropriate. I also compared two rivers between old and new rapid- the directionality looks correct to me. 

l) Can you send a screenshot showing what you see under natural features and waterways? Detailed repro steps would help as well- are you clicking on a newly drawn way or area in order to see them? 


r) Hot Springs are depicted as a white node instead with the hot water logo of ID
I can't seem to reproduce this in v2- RapiD v1 has this problem, but v2 should work! 

Here's what I see when I add a hot spring: 

![image](https://user-images.githubusercontent.com/1887955/219448690-632f7e50-e2ff-44c5-b64b-13d7e0eb13ae.png)



 In the future, would you mind submitting bugs from within Rapid using the bug nub?  That automatically records where you were looking on the map and speeds up our ability to reproduce issues significantly 👍 Screenshots are also extremely helpful. 
 
Once again, thanks so much for your detailed writeup here!
 
![image](https://user-images.githubusercontent.com/1887955/219447803-3bf960d4-3a42-4eaf-b7ea-2d9500d34db0.png)

**Comment by jjiglesiasg** [comment] 2023-02-17 23:00
Should have captured some screenshoot to show the problems. will Report future issues with the bug button.

Thanks and very nice work to improve RAPID. 

I am a regular user and love the help given, however I do not ever convert to actual lines the road suggestions, becuase several of them are quite crude, and I rather to map with more detail, even in the backcountry areas.
BsRgds

**Comment by jjiglesiasg** [comment] 2023-02-18 07:33
n) Closed areas with a name now do have a centroid node- this is intentional! Can you describe what is confusing about it? 
Tradicionally areas show their name but do not show any element that could be confused with other. Clear separation between the structure of NODE, LINES, AREAS. Adding a centroid nodes create like and hibrid between Nodes and Areas.

In particular for me is confusing, because Areas could englobe several nodes inside, is like creating a false one....

**Comment by bhousel** [comment] 2024-07-11 14:43
Closing here, as all the items have been moved to other issues and closed separately 👍

**Closed by bhousel** 2024-07-11 14:43 UTC
Labels: feature-usability
