### ISSUE TITLE
Unable to select more than one features

### ISSUE THREAD

**Issue by VLD190** [facebook/RapiD#707] opened 2022-12-07 17:25 UTC
### Description

I selected a node within a building, and I attempted to select another node so that I can move both at the same time. Unfortunately I was unable to select both nodes. 

As an extension, I attempted to select two areas, or two ways, or a mixture of different features but RapiD V2 Alpha 3 was unable to select multiple features.

### Version

2.00-alpha.3

### What browser are you seeing the problem on? What version are you running?

Chrome v108.0

### Steps to reproduce

left-click a feature (node, way or area), and try selecting another feature by holding 'shift' and left-clicking another feature.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.95/33.92377/-116.54600

**Comment by Bonkles** [comment] 2022-12-13 15:35
Duplicate of #635, closing!

**Closed by Bonkles** 2022-12-13 15:35 UTC
