### ISSUE TITLE
Unable to navigate streetview with keyboard arrows 

### ISSUE THREAD

**Issue by ee-scaduto** [facebook/Rapid#551] opened 2022-08-17 21:52 UTC
### Description

A regression in RapiD v2 was spotted where once in Map Data > Photo Overlays with streetview toggled on e.g. Mapillary, Bing Streetside, we are unable to use the arrow keys from the keyboard to proceed in any direction i.e. forward/backward -- this functionality was previously available in v1. Pressing the arrow key navigates the main page rather than the pop-up streetview window. Note that the buttons within the window works fine, such as the zoom -/+, auto play, etc. 
<img width="1259" alt="Screen Shot 2022-08-17 at 2 45 33 PM" src="https://user-images.githubusercontent.com/111464495/185249581-4a4bedf3-aa88-4c6b-b0aa-337d2ffe1c28.png">

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Edge v104.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.24/37.76257/-122.48350&photo=mapillary/157412386316434&photo_overlay=mapillary

**Comment by Bonkles** [comment] 2022-08-18 15:24
Thanks for the bug report!  Possibly a duplicate of #504, we'll have to take a closer look once we're back from FOSS4G.

**Closed** 2023-10-04 17:39 UTC
Labels: bug, feature-streetview, mapillary
