### ISSUE TITLE
Selecting a line or an area has become more difficult

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#905] opened 2023-04-06 06:44 UTC
### Description

Everytime that you want to select a line or an area the selection goes straight to a node, and you need to zoom a lot in order to touch the line between the two adjacent nodes, so the way/area them could be selected.

### Version

2.0.1

### What browser are you seeing the problem on? What version are you running?

Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### The OS you're using

Win10

### Steps to reproduce

Just look for a way (Any) or area (Any) with several nodes and try to select that way or area, and the selector jump to a node.  You them need to unselect and zoom a lot and them select again

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w577493969&map=16.60/-18.08262/-63.97502

**Comment by repairfox** [comment] 2023-04-07 20:12
Adding to this, it is much more difficult for me to draw driveways for the same reason. If I start from the road, ending at the building, it is not so bad. But starting from a building, then trying to end with the last node on the road is very hard, and I usually have been ending up with multiple errors for this reason every changeset now.

**Comment by bhousel** [comment] 2023-04-08 13:50
Thanks! this is a duplicate of #863 
It's my top priority to get this working better.  I was looking into it last week and I think it might be related to some recent changes in Pixi's interactivity with Pixi v7.x, so I'm hoping that bumping to a newer Pixi version gets us closer to the expected behavior.

**Closed by bhousel** 2023-04-08 13:50 UTC
