### ISSUE TITLE
REQ: adjustable offset to suggested building outlines

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#1352] opened 2024-03-25 04:06 UTC
### Description

In Hungary we have an aerial image provider which gave permission for the OSM community. The company is "FÖMI". 
Sometimes the mapwithai suggested building outlines and the bacground image match without noticable offset.
However we often observe a bigger offset (5-10 meters) between the mapwithai suggested building outlines and the bacground image, provided by FÖMI. (we regard the images of FÖMI have precise geo references).
In these cases the buildings must be moved by hand, one by one. This is a tedious process.

That big offset is unacceptable by the Hungarian community. 
Probably other editors also think the image offset must be as low as possible.

FÖMI images can only be used over Hungary, as the pictures were made especially for this country.
But I think that the possibility to give offset to background image would be useful anywhere, where you obtain a reliable, precise geo references (for example with RTK GPS devices or by other methods).

Suggestion: Please add a user controllable offset to the building outlines.
This would work like the offset for the selected background image.

### Screenshots

![2024-03-25 mapwithai offset](https://github.com/facebook/Rapid/assets/11352049/e4fef305-2746-445f-9f03-189501dffd93)

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Firefox v124.0

### The OS you're using

win

### Steps to reproduce

1. go to any village in Hungary
2. select "FÖMI 2010" as background image
3. see the suggested buildings
4. compare to background image

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=FOMI_2007_2010&datasets=fbRoads,msBuildings&disable_features=landuse,pistes,aerialways,power,past_future&id=r1273069&map=19.15/47.13994/20.37854

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0

**Comment by bhousel** [comment] 2024-04-18 22:14
I agree, users should be able to adjust the alignment of the data layers independently of the imagery layers.  This is a duplicate of issue #270

**Closed by bhousel** 2024-04-18 22:14 UTC

**Comment by misibacsi** [comment] 2024-04-19 01:03
But issue https://github.com/facebook/Rapid/issues/270 is from 2021 and it is still "open".
When will it be implemented?
