### ISSUE TITLE
[Style Options] No fill (Wireframe) makes it impossible to click on buildings. 

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#1004] opened 2023-08-03 16:56 UTC
### Description

If I choose the no fill (wireframe) style then it seems impossible to select or edit buildings. Once I choose the partial or full fill I am able to select the building and edit.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome v115.0

### The OS you're using

mac

### Steps to reproduce

Choose "No fill (Wireframe)" style option and then try to click on a building.

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=21.15/-31.97795/115.78804

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by bhousel** [comment] 2023-08-03 18:04
thanks!  this is a duplicate of #983 👍

**Closed by bhousel** 2023-08-03 18:04 UTC
