### ISSUE TITLE
When drawing a line, if you try to pan the entire line goes away.

### ISSUE THREAD

**Issue by Busterama452** [facebook/Rapid#891] opened 2023-04-04 05:03 UTC
### Description

When I'm drawing lines on the map if I click-hold and pan the map to see more the entire way I just drew goes away when I unclick.

### Version

2.0.0 beta

### What browser are you seeing the problem on? What version are you running?

chrome

### The OS you're using

Windows 10

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Maxar-Premium&datasets=fbRoads,msBuildings,e75b56f13b404d7d8b47ef8be1c619ec&id=w709663916&map=16.84/33.03699/-113.28807

**Comment by mvexel** [comment] 2023-04-04 17:43
Thanks for reporting! This looks like a duplicate of #879. Let's track the issue there.

**Closed by mvexel** 2023-04-04 17:43 UTC
