### ISSUE TITLE
Microsoft Buildings are not always loaded

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#1330] opened 2024-02-10 05:07 UTC
### Description

In the last few weeks the **Microsoft Buildings** are not loaded so fast as usual (within seconds). 
Very often it takes about **1 minute** when the buildings appear. 
If not, I usually do a page reload (Ctrl-R in Firefox), and then the buildings outlines are loaded (or not).
I talk about the buildings which already had an outline, but I did not edit them yet because of changeset limit.
After I upload the changeset, the previously visible outlines disappear.
Very frustrating.

### Screenshots

(see image in my next comment)

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Firefox v122.0

### The OS you're using

win

### Steps to reproduce

1. edit buildings 
2. upload changeset
3. wait for the buildings outline to appear

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=FOMI_2007_2010&datasets=fbRoads,msBuildings&disable_features=landuse,pistes,aerialways,power,past_future&map=17.78/46.17711/17.31791

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0

**Comment by misibacsi** [comment] 2024-02-10 05:22
![2024-02-09 OSM Rapid MS buildings load failure](https://github.com/facebook/Rapid/assets/11352049/99a6f4e5-aeb9-4e53-a703-347b57b60912)

**Comment by bhousel** [comment] 2024-02-10 14:15
Thanks, I think this is a duplicate of #1295, which is tracking improvements to our service that conflates the Microsoft buildings against the OSM buildings.  We're working on it!
cc @Bonkles

**Closed by bhousel** 2024-02-10 14:15 UTC
