### ISSUE TITLE
Node position editing in relations is slow

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#973] opened 2023-06-30 13:59 UTC
### Description

There might already be another bug about this but I could not find it... basically, when I'm very zoomed in so there is not much on my screen and I try to edit a sizable relation (r1240554) it is just dreadfully slow to edit the location of nodes associated with that relation. I don't remember having this issue with the old version.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome v114.0

### The OS you're using

mac

### Steps to reproduce

Zoom in to a spot on the Kissimmee River and try to drag one of the nodes to a new place. The performance makes it tough to deal with.

https://github.com/facebook/Rapid/assets/5851115/404c78d6-b122-4052-b361-76dd485a088b

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w82547281&map=21.43/27.65957/-81.13432

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by bhousel** [comment] 2024-04-18 21:10
Hey Alex, sorry I didn't respond sooner!
I did some investigation and this issue is actually a duplicate of #544 

When zoomed in this far, and particularly when working with large features like the Kissimmee River, our labeling code can be really inefficient.  It's trying to place labels all around the river, when really it should only stick to the part of the river around where the user is looking.

![Screenshot 2024-04-18 at 5 07 31 PM](https://github.com/facebook/Rapid/assets/38784/6884b360-7dac-4b58-8dbe-c0b98490d088)

**Closed by bhousel** 2024-04-18 21:10 UTC
