### ISSUE TITLE
Microsoft Buildings are shown but already exist

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#1331] opened 2024-02-10 05:38 UTC
### Description

In the last few weeks sometimes the building outlines appear, even the buildings are already exist (edited and uploaded).

### Screenshots
AI suggestions are shown for already existing buildings:
![2024-02-10 OSM Rapid MS buildings are shown but already exist 2](https://github.com/facebook/Rapid/assets/11352049/d89a609e-df1b-4ee2-b125-adef9907f9f3)

![2024-02-10 OSM Rapid MS buildings are shown but already exist](https://github.com/facebook/Rapid/assets/11352049/7195a3df-a214-4cec-8603-cd05b842cd6b)

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Firefox v122.0

### The OS you're using

win

### Steps to reproduce

1. edit buildings
2. upload changeset
3. look at the previously edited area

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=FOMI_2007_2010&datasets=fbRoads,msBuildings&disable_features=landuse,pistes,aerialways,power,past_future&map=18.26/46.17578/17.31845

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0

**Comment by bhousel** [comment] 2024-02-10 14:16
Thanks, I think this is a duplicate of #1295, which is tracking improvements to our service that conflates the Microsoft buildings against the OSM buildings.  We're working on it!
cc @Bonkles

**Closed by bhousel** 2024-02-10 14:16 UTC
Labels: duplicate
