### ISSUE TITLE
Snapping only works when moving the pointer quickly

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#688] opened 2022-12-05 18:30 UTC
### Description

This may be intended behavior?

In drawing mode, when I move the pointer over an existing geometry, Rapid wants to snap to that, but *only* if I move the pointer at reasonably fast speed. Perhaps the following video illustrates:

https://user-images.githubusercontent.com/120452/205714032-bc46751f-d286-4819-978b-a86b7b4d8616.mov

### Version

2.00-alpha3

### What browser are you seeing the problem on? What version are you running?

Firefox 107 Mac

### Steps to reproduce

1. Start drawing a line
2. While drawing the line, move the pointer over an existing line or area feature
3. Snapping behavior will occur only when moving the pointer fast.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&map=23.71/40.74003/-111.86058

**Comment by Bonkles** [comment] 2022-12-06 14:56
This is TOTALLY a bug. 

Overly Detailed Explanation For Posterity: 
The problem is that we calculate 'hit targets' for everything on the screen.  Right now, during the 'add area' or 'add line' modes, you can snap to ways and points just fine, because we explicitly tell the rendering subsystem 'yo, this thing we're drawing? Don't draw hit targets for the node/way that the mouse pointer is attached to, we are more interested in the other stuff on the screen'. 

By eliminating the hit target for the stuff attached to the pointer, we allow the system to detect the other things (ways, points, etc) that we're hovering over and 'snap' to them. 

The fix in this case will be to also tell the renderer 'hey, we're not adding a completely new area or way here- we're just dragging a single node. while we're dragging this node, hide its hit target from the scene so we 'see' the things underneath'. 

The reason that moving the mouse pointer so fast works is that- the mouse pointer *outruns* the shape it's attached to, and so for a brief second, before pixi has caught up and recalculated the position / hit target for the attached way & point, the mouse is able to 'hover' over another thing in the map.

**Comment by Bonkles** [comment] 2022-12-06 15:19
"But Ben", I hear you saying, "Why can I snap to nodes without having to move the mouse pointer fast, but not ways?"

Another good question! This has to do with the way we stack nodes and ways in the scene graph. Essentially, nodes are drawn 'on top' of ways, which means that we do a better job of detecting when the user is dragging a point over another point. Dragging a point over a way will almost certainly obscure the way, as the way is 'further down' the hit target priority list.

**Comment by Bonkles** [comment] 2022-12-06 15:28
Fixed in `74bd30d07`.

**Closed by Bonkles** 2022-12-06 15:28 UTC
