### ISSUE TITLE
Rotate tool not functioning

### ISSUE THREAD

**Issue by vld165** [facebook/Rapid#1548] opened 2024-09-10 16:13 UTC
### Description

After adding new geometry, user attempted to rotate the building using rotate tool, but it was unresponsive

### Version

2.4.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Chrome v128.0

### The OS you're using

mac

### Steps to reproduce

Accept Rapid building suggestion.
Add tags to building
Right click and select rotate

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=20.27/41.76181/-71.35183&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-4

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Comment by eneerhut** [comment] 2024-09-26 10:44
I was not able to reproduce this either. Are you still encountering this @vld165? If so, can you take a video?

**Comment by bhousel** [comment] 2024-11-27 21:35
Closing, as this seems to be working in latest canary..

**Closed by bhousel** 2024-11-27 21:35 UTC
Labels: waitfor-cant-repro
